[tasks]
list = "rig run --list"
help = "rig --help"
build = "go build ./..."
test = "go test ./..."
vet = "go vet ./..."
fmt = "gofmt -s -w ."
run = "go run ."
lint = "golangci-lint run ./..."
dev = "reflex -r \".\\.go$\" -- sh -c 'go run . '"
